export const VIEWS = [
  "posta",
  "posta-running",
  "posta-empty",
  "posta-loading",
  "posta-grayscale",
  "pull-pulling",
  "pull-armed",
  "pull-blocked",
  "pull-live",
  "carousel",
  "viewer",
  "budget-lock",
  "modes-friends",
  "modes-creators",
  "expired",
  "expired-error",
  "messaggi",
  "messaggi-empty",
  "messaggi-long",
  "thread",
  "thread-off",
  "thread-stale",
  "thread-failed",
  "salvati",
  "salvati-empty",
  "salvati-open",
  "profilo",
  "profilo-budget",
  "profilo-theme",
  "profilo-dm-confirm",
  "login",
  "register",
  "pair",
  "error",
] as const;

export type GalleryViewName = (typeof VIEWS)[number];
