from typing import Protocol

from ig_engine.schemas import (
    Comment,
    LoginResult,
    Message,
    Post,
    PostsPage,
    Profile,
    Story,
    Thread,
    TimelinePage,
    TrayEntry,
    User,
)

type SessionSettings = dict[str, object]


class InstagramClient(Protocol):
    def load_settings(self, settings: SessionSettings) -> None: ...

    def export_settings(self) -> SessionSettings: ...

    def login(self, sessionid: str) -> str: ...

    def login_with_credentials(
        self, username: str, password: str, verification_code: str
    ) -> LoginResult: ...

    def following(self, amount: int) -> list[User]: ...

    def followers(self, amount: int) -> list[User]: ...

    def user_posts(
        self, user_id: str, amount: int, cursor: str | None, include_reels: bool
    ) -> PostsPage: ...

    def stories_tray(self) -> list[TrayEntry]: ...

    def user_stories(self, user_id: str) -> list[Story]: ...

    def user_profile(self, user_id: str) -> Profile: ...

    def comments(self, media_id: str, amount: int) -> list[Comment]: ...

    def like(self, media_id: str) -> None: ...

    def unlike(self, media_id: str) -> None: ...

    def save(self, media_id: str) -> None: ...

    def unsave(self, media_id: str) -> None: ...

    def add_comment(self, media_id: str, text: str) -> None: ...

    def delete_comment(self, media_id: str, comment_id: str) -> None: ...

    def timeline(self, cursor: str | None) -> TimelinePage: ...

    def saved(self, amount: int) -> list[Post]: ...

    def threads(self, amount: int) -> list[Thread]: ...

    def messages(self, thread_id: str, amount: int) -> list[Message]: ...

    def send_message(self, thread_id: str, text: str) -> Message: ...
