from typing import Protocol

from ig_engine.schemas import Message, Post, Thread, TimelinePage, User

type SessionSettings = dict[str, object]


class InstagramClient(Protocol):
    def load_settings(self, settings: SessionSettings) -> None: ...

    def export_settings(self) -> SessionSettings: ...

    def login(self, sessionid: str) -> str: ...

    def following(self, amount: int) -> list[User]: ...

    def followers(self, amount: int) -> list[User]: ...

    def user_posts(self, user_id: str, amount: int) -> list[Post]: ...

    def timeline(self, cursor: str | None) -> TimelinePage: ...

    def saved(self, amount: int) -> list[Post]: ...

    def threads(self, amount: int) -> list[Thread]: ...

    def messages(self, thread_id: str, amount: int) -> list[Message]: ...

    def send_message(self, thread_id: str, text: str) -> Message: ...
